### ISSUE TITLE
[Orb Enhancement] Executor enhancements.

### ISSUE THREAD

**Issue by KyleTryon** [Probely/probely-orb#1]
1. Consider renaming the included "alpine" executor to "default".
2. Add a parameter to control the Docker tag version
3. Update any jobs referencing "alpine" to switch to "default" and include the version parameter.

Executor: https://github.com/Probely/probely-orb/blob/master/src/executors/alpine.yml
Best practices: https://circleci.com/docs/2.0/orbs-best-practices/#executors

_Consider adding the `orbtoberfest` label on this issue to make this issue eligible for #Orbtoberfest https://circleci-public.github.io/hacktoberfest_

**Comment by fortrieb** [comment]
I will take this issue if nobody is working on it.
